<a href="https://colab.research.google.com/github/przemyslawroch/machine-learning-bootcamp/blob/main/supervised/01_basics/data_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import sklearn

≈Åadowanie danych

In [16]:
def fetch_financial_data(company='AMZN'):
  """this function fetches stock market quotations
  """
  import pandas_datareader.data as web
  return web.DataReader(name=company, data_source='stooq')

df_raw = fetch_financial_data()
df_raw.head()

               Open     High      Low    Close   Volume
Date
2022-03-08  2733.67  2813.99  2671.45  2720.29  4583129
2022-03-07  2908.87  2921.89  2748.33  2749.06  4346693
2022-03-04  2943.18  2957.00  2876.14  2912.82  3049156
2022-03-03  3070.63  3078.58  2937.12  2957.97  3259860
2022-03-02  3018.15  3059.99  2975.00  3041.05  2366736

Tworzenie kopii

In [23]:
df = df_raw.copy()
df = df[:5]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2022-03-08 to 2022-03-02
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5 non-null      float64
 1   High    5 non-null      float64
 2   Low     5 non-null      float64
 3   Close   5 non-null      float64
 4   Volume  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

Generowanie nowych zmiennych

In [21]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

               Open     High      Low    Close   Volume  day  month  year
Date
2022-03-08  2733.67  2813.99  2671.45  2720.29  4583129    8      3  2022
2022-03-07  2908.87  2921.89  2748.33  2749.06  4346693    7      3  2022
2022-03-04  2943.18  2957.00  2876.14  2912.82  3049156    4      3  2022
2022-03-03  3070.63  3078.58  2937.12  2957.97  3259860    3      3  2022
2022-03-02  3018.15  3059.99  2975.00  3041.05  2366736    2      3  2022

Dyskretyzacja zmiennej ciƒÖg≈Çej

In [24]:
df = pd.DataFrame(data={'height': [175., 178.5, 185., 191., 184.5, 183., 168.]})
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [25]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195), labels=['small', 'medium', 'high'])
df

   height height_cat
0   175.0      small
1   178.5     medium
2   185.0       high
3   191.0       high
4   184.5       high
5   183.0       high
6   168.0      small

In [26]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_medium  height_high
0   175.0              0            0
1   178.5              1            0
2   185.0              0            1
3   191.0              0            1
4   184.5              0            1
5   183.0              0            1
6   168.0              0            0

Ekstrakcja cech

In [27]:
df = pd.DataFrame(data={'lang': [['PL', 'ENG'], ['GER', 'ENG', 'PL', 'FRA'], ['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [28]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [29]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [30]:
df = pd.DataFrame(data={'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [31]:
df.website.str.split('.', expand=True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [32]:
new = df.website.str.split('.', expand=True)
df['portal'] = new[0]
df['extension'] = new[1]
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com